# Default values for gtm-server.

image:
  repository: gcr.io/cloud-tagging-10302018/gtm-cloud-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stable"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

sst:
  replicaCount: 3
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []
  service:
    type: ClusterIP
    port: 8080

preview: 
  serverUrl: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []
  service:
    type: ClusterIP
    port: 8080

extraEnv: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
