# Default values for gtm-server.

replicaCount: 3

previewServerUrl: ""

image:
  repository: gcr.io/cloud-tagging-10302018/gtm-cloud-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stable"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnv: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
