apiVersion: v1
kind: Service
metadata:
  name: {{ include "gtm-server.previewName" . }}
  labels:
    {{- include "gtm-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.preview.service.type }}
  ports:
    - port: {{ .Values.preview.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gtm-server.previewSelectorLabels" . | nindent 4 }}
